/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <iostream>
#include <stdlib.h>


class calculation{
private:
    int add_a;
    int add_b;
    int sub_a;
    int sub_b;


public:
    int calculation_result;
    int add_number(int add_a, int add_b);
    int sub_number(int sub_a, int sub_b);
    float square(volatile int *p);
};
float calculation::square(volatile int *p){

    return *p * *p;
}

int calculation::add_number(int add_a, int add_b)
{
    return add_a + add_b;
}


int calculation::sub_number(int sub_a, int sub_b)
{
    return sub_a - sub_b;
}

int main(void)
{

    calculation cal;
    
    while (1) {
    
    /* Loop forever */
    cal.calculation_result= cal.add_number(1, 2);

    cal.calculation_result= cal.add_number(-1,-2);

    cal.calculation_result= cal.add_number(65535, 1);

    cal.calculation_result = cal.sub_number(2, 1 );

    cal.calculation_result = cal.square((volatile int *)2);


    }
}

